[project]
authors = ["Kresna Sucandra <kresnasucandra@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
name = "mojo-matrix-multiply"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "*"
